# Generated by Django 5.0.1 on 2024-01-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256, verbose_name='Deskripsi Permohonan Data')),
                ('name', models.CharField(max_length=256, verbose_name='Nama Pemohon')),
                ('contact', models.CharField(max_length=15, verbose_name='Kontak Pemohon')),
                ('agency', models.CharField(max_length=256, verbose_name='Instansi Pemohon')),
                ('desc_data', models.TextField(verbose_name='Deskripsi Data')),
                ('app_letter', models.FileField(upload_to='requst_form_letter', verbose_name='Surat Permohonan')),
                ('status', models.CharField(choices=[('0', 'Menunggu Persetujuan'), ('1', 'Memproses Permintaan Data'), ('2', 'Data Belum Tersedia (Belum Rilis)'), ('3', 'Permohonan Data Ditolak')], default=0, max_length=1, verbose_name='Status Permohonan')),
            ],
        ),
        migrations.CreateModel(
            name='MessagesRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=15, verbose_name='Pesan untuk Pemohon')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_req_form', to='homepage.datarequestform')),
            ],
        ),
    ]
