# Generated by Django 5.0.1 on 2024-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_agency_datarequestform_agency_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='Pertanyaan')),
                ('answer', models.TextField(verbose_name='Jawaban')),
            ],
        ),
    ]
