# Generated by Django 5.0.1 on 2024-08-15 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_faqmodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodels',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AddField(
            model_name='faqmodels',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
