# Generated by Django 5.0.1 on 2024-01-17 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backendcharacteristicsmodel',
            options={'verbose_name': 'Master Karakteristik', 'verbose_name_plural': 'Master Karakteristik'},
        ),
        migrations.AlterModelOptions(
            name='backendindicatorsmodel',
            options={'verbose_name': 'Master Tabel Statistik', 'verbose_name_plural': 'Master Tabel Statistik'},
        ),
        migrations.AlterModelOptions(
            name='backendinfographicsmodel',
            options={'verbose_name': 'Master Infografis', 'verbose_name_plural': 'Master Infografis'},
        ),
        migrations.AlterModelOptions(
            name='backendperiodsmodel',
            options={'verbose_name': 'Periode Waktu Statistik', 'verbose_name_plural': 'Periode Waktu Statistik'},
        ),
        migrations.AlterModelOptions(
            name='backendrowsmodel',
            options={'verbose_name': 'Master Judul Baris', 'verbose_name_plural': 'Master Judul Baris'},
        ),
        migrations.AlterModelOptions(
            name='backendstatsnewsmodel',
            options={'verbose_name': 'Berita Statistik', 'verbose_name_plural': 'Berita Statistik'},
        ),
        migrations.AlterModelOptions(
            name='backendsubjectsmodel',
            options={'verbose_name': 'Master Subject', 'verbose_name_plural': 'Master Subject'},
        ),
        migrations.AlterModelOptions(
            name='backendsubjectsscamodel',
            options={'verbose_name': 'Master Subject SCA', 'verbose_name_plural': 'Master Subject SCA'},
        ),
        migrations.AlterModelOptions(
            name='backendunitsmodel',
            options={'verbose_name': 'Satuan Data Statistik', 'verbose_name_plural': 'Satuan Data Statistik'},
        ),
        migrations.AlterModelOptions(
            name='backendvideographicsmodel',
            options={'verbose_name': 'Master Videografis', 'verbose_name_plural': 'Master Videografis'},
        ),
        migrations.CreateModel(
            name='BackendContentIndicatorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, verbose_name='Tahun Indikator')),
                ('item_period', models.CharField(max_length=1, verbose_name='Periode Waktu')),
                ('item_char', models.CharField(max_length=1)),
                ('item_row', models.CharField(max_length=1)),
                ('value', models.FloatField(null=True, verbose_name='Nilai Tabel')),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_indicator', to='backend.backendindicatorsmodel')),
            ],
            options={
                'verbose_name': 'Master Konten Tabel',
                'verbose_name_plural': 'Master Konten Tabel',
            },
        ),
    ]
