# Generated by Django 5.0.1 on 2024-01-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_backendindicatorsmodel_subject_csa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='col_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cols_indicator', to='backend.backendcharacteristicsmodel', verbose_name='Kelompok Karakteristik'),
        ),
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='row_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows_indicator', to='backend.backendrowsmodel', verbose_name='Kelompok Judul Baris'),
        ),
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='time_period_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_indicator', to='backend.backendperiodsmodel', verbose_name='Periode Data'),
        ),
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_indicator', to='backend.backendunitsmodel', verbose_name='Satuan'),
        ),
    ]
