# Generated by Django 5.0.1 on 2024-01-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_backendindicatorsmodel_col_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='subject_csa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_indicator', to='backend.backendsubjectsscamodel'),
        ),
    ]
