# Generated by Django 5.0.1 on 2024-01-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_backendindicatorsmodel_subject_csa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendunitsmodel',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Satuan'),
        ),
    ]
