# Generated by Django 5.0.1 on 2024-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_backendcontentindicatorsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='item_char',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Item Karakteristik Waktu'),
        ),
    ]
