# Generated by Django 5.0.1 on 2024-01-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_backendcontentindicatorsmodel_item_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='item_char',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Item Karakteristik Waktu'),
        ),
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='item_period',
            field=models.CharField(max_length=5, verbose_name='Periode Waktu'),
        ),
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='item_row',
            field=models.CharField(max_length=5, verbose_name='Item Judul Baris'),
        ),
    ]
