# Generated by Django 5.0.1 on 2024-01-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_backendcontentindicatorsmodel_item_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Nilai'),
        ),
    ]
