# Generated by Django 5.0.1 on 2024-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_backendcontentindicatorsmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='Nilai'),
        ),
    ]
