# Generated by Django 5.0.1 on 2024-01-30 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_backendcontentindicatorsmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendcontentindicatorsmodel',
            name='indicator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_indicator', to='backend.backendindicatorsmodel'),
        ),
    ]
