# Generated by Django 5.0.1 on 2024-02-01 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_backendcontentindicatorsmodel_indicator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='file',
            field=models.FileField(upload_to='stats_news', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File Berita'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='subject_csa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_stat_news', to='backend.backendsubjectsscamodel'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail-statsnews', verbose_name='Thumbnail Berita'),
        ),
    ]
