# Generated by Django 5.0.1 on 2024-02-02 15:40

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_backendstatsnewsmodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendstatsnewsmodel',
            name='author',
            field=models.CharField(default='BPS Kabupaten Muna', max_length=128, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='file',
            field=models.FileField(upload_to='stats_news', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_file_size], verbose_name='File Berita'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='num_visits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail-statsnews', validators=[backend.validators.validate_file_size], verbose_name='Thumbnail Berita'),
        ),
    ]
