# Generated by Django 5.0.1 on 2024-02-03 11:01

import backend.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_backendstatsnewsmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendinfographicsmodel',
            name='file',
            field=models.FileField(upload_to='infographics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_file_size], verbose_name='File Infografis'),
        ),
        migrations.AlterField(
            model_name='backendinfographicsmodel',
            name='num_visits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='backendinfographicsmodel',
            name='subject_csa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_infographic', to='backend.backendsubjectsscamodel'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='subject_csa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_stat_news', to='backend.backendsubjectsscamodel', verbose_name='Subjek CSA'),
        ),
        migrations.AlterField(
            model_name='backendstatsnewsmodel',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_stat_news', to='backend.backendsubjectsmodel', verbose_name='Subjek Statistik'),
        ),
        migrations.AlterField(
            model_name='backendvideographicsmodel',
            name='subject_csa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_videographic', to='backend.backendsubjectsscamodel'),
        ),
    ]
