# Generated by Django 5.0.1 on 2024-02-03 13:56

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_backendinfographicsmodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendvideographicsmodel',
            name='file',
            field=models.FileField(upload_to='videographics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_file_size], verbose_name='File Videografis'),
        ),
        migrations.AlterField(
            model_name='backendvideographicsmodel',
            name='num_visits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='backendvideographicsmodel',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail-videographics', validators=[backend.validators.validate_file_size], verbose_name='Thumbnail Videografis'),
        ),
    ]
