# Generated by Django 5.0.1 on 2024-02-03 14:40

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_backendvideographicsmodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendvideographicsmodel',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Link Youtube'),
        ),
        migrations.AlterField(
            model_name='backendvideographicsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videographics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv']), backend.validators.validate_video_file_size], verbose_name='File Videografis'),
        ),
    ]
