# Generated by Django 5.0.1 on 2024-02-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_backendvideographicsmodel_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendContentStatisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Judul Tabel')),
                ('content', models.TextField(verbose_name='Konten HTML')),
                ('show_state', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], max_length=1, verbose_name='Tampilkan Infografis')),
                ('subject_csa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_csa_content_static', to='backend.backendsubjectsscamodel')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_content_static', to='backend.backendsubjectsmodel')),
            ],
            options={
                'verbose_name': 'Master Konten Tabel Statis',
                'verbose_name_plural': 'Master Konten Tabel Statis',
            },
        ),
    ]
