# Generated by Django 5.0.1 on 2024-02-06 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_backendcontentstatismodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='desc',
            field=models.TextField(default='Ini desc', verbose_name='Deskripsi Tabel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='footer_desc',
            field=models.CharField(default='sumber BPS Kab. Muna', max_length=512, verbose_name='Keterangan Tabel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='stat_category',
            field=models.CharField(choices=[('1', 'Dasar'), ('2', 'Sektoral')], default='1', max_length=1, verbose_name='Kategori Statistik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='backendcontentstatismodel',
            name='year',
            field=models.CharField(default=2024, max_length=5, verbose_name='Tahun Tabel'),
            preserve_default=False,
        ),
    ]
