# Generated by Django 5.0.1 on 2024-02-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_backendcontentstatismodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendcontentstatismodel',
            name='desc',
        ),
    ]
