# Generated by Django 5.0.1 on 2024-02-07 04:41

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_backendcontentstatismodel_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendDataRequestsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=128, verbose_name='Nama Pemohon')),
                ('contact_person', models.CharField(max_length=128, verbose_name='Kontak Pemohon')),
                ('agency_person', models.CharField(max_length=128, verbose_name='Instansi Pemohon')),
                ('subject_request', models.CharField(max_length=128, verbose_name='Judul Permohonan Data')),
                ('desc_data', models.TextField(verbose_name='Deskripsi Data yang Dimaksudkan')),
                ('app_letter', models.FileField(null=True, upload_to='letter_data_request', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_file_size], verbose_name='Unggah Surat Permohonan')),
                ('request_at', models.DateField(auto_now_add=True)),
                ('approved_at', models.DateField(null=True, verbose_name='Tanggal Disetujui')),
                ('show_state', models.CharField(choices=[('1', 'Disetujui'), ('2', 'Data Tidak/Belum Tersedia'), ('3', 'Menunggu Konfirmasi PIC')], max_length=1, verbose_name='Status Permohonan Data')),
            ],
            options={
                'verbose_name': 'Permohonan Data',
                'verbose_name_plural': 'Permohonan Data',
            },
        ),
    ]
