# Generated by Django 5.0.1 on 2024-02-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_backenddatarequestsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddatarequestsmodel',
            name='show_state',
            field=models.CharField(choices=[('1', 'Disetujui'), ('2', 'Data Tidak/Belum Tersedia'), ('3', 'Menunggu Konfirmasi PIC')], default='3', max_length=1, verbose_name='Status Permohonan Data'),
        ),
    ]
