# Generated by Django 5.0.1 on 2024-02-07 04:45

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_backenddatarequestsmodel_show_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddatarequestsmodel',
            name='app_letter',
            field=models.FileField(blank=True, null=True, upload_to='letter_data_request', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_file_size], verbose_name='Unggah Surat Permohonan'),
        ),
        migrations.AlterField(
            model_name='backenddatarequestsmodel',
            name='approved_at',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Disetujui'),
        ),
    ]
