# Generated by Django 5.0.1 on 2024-02-07 13:52

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_backendpublicationsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='abstract',
            field=models.TextField(verbose_name='Abstrak'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='catalog_no',
            field=models.CharField(max_length=128, verbose_name='Nomor Catalog'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_publication_size], verbose_name='File Publikasi'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='issn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nomor ISSN/ISBN'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='publication_no',
            field=models.CharField(max_length=128, verbose_name='Nomor Publikasi'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='release',
            field=models.DateField(verbose_name='Tanggal Release'),
        ),
    ]
