# Generated by Django 5.0.1 on 2024-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_backendpublicationsmodel_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='catalog_no',
            field=models.CharField(max_length=50, verbose_name='Nomor Catalog'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor ISSN/ISBN'),
        ),
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='publication_no',
            field=models.CharField(max_length=50, verbose_name='Nomor Publikasi'),
        ),
    ]
