# Generated by Django 5.0.1 on 2024-02-07 14:57

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_backendpublicationsmodel_catalog_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='file',
            field=models.FileField(default='test', upload_to='publications', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), backend.validators.validate_publication_size], verbose_name='File Publikasi'),
            preserve_default=False,
        ),
    ]
