# Generated by Django 5.0.1 on 2024-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_backendpublicationsmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendpublicationsmodel',
            name='revision_log',
            field=models.IntegerField(default=0),
        ),
    ]
