# Generated by Django 5.0.1 on 2024-02-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_backendpublicationsmodel_revision_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendindicatorsmodel',
            name='level_data',
            field=models.CharField(choices=[('0', 'Indikator Biasa'), ('1', 'Indikator Strategis'), ('2', 'Indikator Pembangunan')], default='0', max_length=1, verbose_name='Level Data'),
        ),
    ]
