# Generated by Django 5.0.1 on 2024-03-27 02:25

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_backendindicatorsmodel_level_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendpublicationsmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail-publications', validators=[backend.validators.validate_file_size], verbose_name='Thumbnail Publication'),
        ),
    ]
