# Generated by Django 5.0.1 on 2024-03-27 03:39

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_backendpublicationsmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendinfographicsmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail-infographics', validators=[backend.validators.validate_file_size], verbose_name='Thumbnail Infographics'),
        ),
    ]
