# Generated by Django 5.0.1 on 2024-03-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_backendinfographicsmodel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendDataConsultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nama')),
                ('contact', models.CharField(max_length=128, verbose_name='Nomor Telp')),
                ('email', models.CharField(max_length=128, verbose_name='Email Pemohon')),
                ('subject', models.CharField(max_length=512, verbose_name='Subjek Pesan')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('state_solved', models.CharField(choices=[('0', 'Belum Diproses'), ('1', 'Ya'), ('2', 'Tidak')], default='0', max_length=1, verbose_name='Status Pesan')),
            ],
            options={
                'verbose_name': 'Konsultasi Data',
                'verbose_name_plural': 'Konsultasi Data',
            },
        ),
        migrations.CreateModel(
            name='BackendDataConsultResponsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Feedback Pesan')),
                ('is_from_admin', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', editable=False, max_length=1, verbose_name='Is from admin?')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('data_consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_consult_respons', to='backend.backenddataconsultmodel', verbose_name='Data Consult Issue')),
            ],
            options={
                'verbose_name': 'Renspons Konsultasi Data',
                'verbose_name_plural': 'Renspons Konsultasi Data',
            },
        ),
    ]
