# Generated by Django 5.0.1 on 2024-03-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_backenddataconsultmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddataconsultresponsmodel',
            name='is_from_admin',
            field=models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], default='2', max_length=1, verbose_name='Is from admin?'),
        ),
    ]
