# Generated by Django 5.0.1 on 2024-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_backenddataconsultresponsmodel_is_from_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenddataconsultmodel',
            name='contact',
            field=models.CharField(max_length=13, verbose_name='Nomor Telp'),
        ),
    ]
