# Generated by Django 5.0.1 on 2024-06-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_backenddataconsultmodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='backenddatarequestsmodel',
            name='email_person',
            field=models.CharField(default=2, max_length=128, verbose_name='Email Pemohon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backenddataconsultmodel',
            name='state_solved',
            field=models.CharField(choices=[('0', 'Belum Diproses'), ('1', 'Sedang Diproses'), ('2', 'Selesai'), ('3', 'Dibatalkan')], default='0', max_length=1, verbose_name='Status Pesan'),
        ),
        migrations.AlterField(
            model_name='backenddatarequestsmodel',
            name='show_state',
            field=models.CharField(choices=[('1', 'Menunggu Konfirmasi PIC'), ('2', 'Diproses'), ('3', 'Disetujui'), ('4', 'Ditolak'), ('5', 'Dibatalkan')], default='3', max_length=1, verbose_name='Status Permohonan Data'),
        ),
        migrations.CreateModel(
            name='BackendIndicatorsMeaningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, verbose_name='Tahun Indikator')),
                ('item_period', models.CharField(max_length=255, verbose_name='Periode Waktu')),
                ('context', models.TextField(verbose_name='Interpretasi Data')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meaning_indicator', to='backend.backendindicatorsmodel')),
            ],
            options={
                'verbose_name': 'Master Interpretasi Tabel',
                'verbose_name_plural': 'Master Interpretasi Tabel',
            },
        ),
    ]
