# Generated by Django 5.0.1 on 2024-06-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_backenddatarequestsmodel_email_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendindicatorsmodel',
            name='summarize_status',
            field=models.CharField(choices=[('0', 'none'), ('1', 'sum'), ('2', 'avg')], default='0', max_length=1, verbose_name='Ringkasan Data'),
        ),
    ]
