# Generated by Django 5.0.1 on 2024-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_backendindicatorsmodel_summarize_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='summarize_status',
            field=models.CharField(choices=[('0', 'none'), ('1', 'sum'), ('2', 'avg'), ('3', 'percent'), ('4', 'Only for data percent')], default='0', max_length=1, verbose_name='Ringkasan Data'),
        ),
    ]
