# Generated by Django 5.0.1 on 2024-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_backendunitsmodel_is_agg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendunitsmodel',
            name='is_viz',
            field=models.CharField(choices=[('0', 'No Visualization'), ('1', 'Bar/Line Chart'), ('2', 'Pie Chart'), ('3', 'Bar/line and Pie Chart')], default='3', max_length=1, verbose_name='Visualisasi Data'),
        ),
        migrations.AlterField(
            model_name='backendunitsmodel',
            name='is_agg',
            field=models.CharField(choices=[('0', 'Ya'), ('1', 'Tidak')], default='1', max_length=1, verbose_name='Apakah dapat diagregasikan?'),
        ),
    ]
