# Generated by Django 5.0.1 on 2024-07-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_backendunitsmodel_is_viz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendunitsmodel',
            name='is_comp',
            field=models.CharField(choices=[('0', 'Tidak'), ('1', 'Ya')], default='1', max_length=1, verbose_name='Apakah dapat dibandingkan?'),
        ),
        migrations.AlterField(
            model_name='backendunitsmodel',
            name='is_agg',
            field=models.CharField(choices=[('0', 'Tidak'), ('1', 'Ya')], default='1', max_length=1, verbose_name='Apakah dapat diagregasikan?'),
        ),
    ]
