# Generated by Django 5.0.1 on 2024-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_backendunitsmodel_is_comp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendperiodnameitemsmodel',
            name='order_item',
            field=models.IntegerField(default=1, verbose_name='Nomor Urut Periode'),
        ),
    ]
