# Generated by Django 5.0.1 on 2024-07-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_backendperiodnameitemsmodel_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendperiodnameitemsmodel',
            name='order_item',
            field=models.IntegerField(verbose_name='Nomor Urut Periode'),
        ),
    ]
