# Generated by Django 5.0.1 on 2024-07-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_backendperiodnameitemsmodel_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendindicatorsmodel',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Sumber Data'),
        ),
    ]
