# Generated by Django 5.0.1 on 2024-07-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_backendindicatorsmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='footer_desc',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Keterangan Indikator'),
        ),
        migrations.AlterField(
            model_name='backendindicatorsmodel',
            name='source',
            field=models.CharField(default='BPS Kabupaten Muna', max_length=512, verbose_name='Sumber Data'),
        ),
    ]
