# Generated by Django 5.0.1 on 2024-08-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_backendindicatorsmodel_footer_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendDashboardSummarizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Judul Item')),
                ('year', models.CharField(max_length=5, verbose_name='Tahun Data')),
                ('item_period', models.CharField(max_length=32, verbose_name='Periode Waktu')),
                ('unit_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Satuan Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Nilai')),
                ('color_tag', models.CharField(blank=True, choices=[('1', 'ribbon-primary'), ('2', 'ribbon-warning'), ('3', 'ribbon-danger'), ('4', 'ribbon-info')], max_length=1, null=True, verbose_name='Color Tag')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag')),
                ('is_show', models.CharField(choices=[('1', 'Ya'), ('2', 'Tidak')], default='1', max_length=1, verbose_name='Tampilkan Data?')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('indicator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_reference', to='backend.backendindicatorsmodel')),
            ],
        ),
    ]
